### ISSUE TITLE
Charm not properly listed as a dependency in-mod

### ISSUE THREAD

**Issue by Bluberry-Kat** [svenhjol/Covalent#1]
This issue report was originally reporting a NullPointerException I was consistently getting during launch, the crash report you can find [here](https://gist.github.com/Birgliss/788ee59fb46f133141585f6ba6e338a2)
I found this is actually not an error, or at least it's an expected one - the version of Charm I have installed is 1.5.7, and this mod depends on at least 1.5.9, as you noted on the curseforge page.
(At the time of writing this issue, 1.5.7 is the most recent version of Charm available on curseforge.)

The problem therein, however, is that this was not listed in the crashlog anywhere. 
As shown below with Quark, if done properly, this screen should appear if the mod is missing a dependency.
![image](https://user-images.githubusercontent.com/20749209/83930651-a7169800-a766-11ea-83dd-a6a5f3521e31.png)

This is not a major issue, but would help make future issues easier to debug and make the mod more user-friendly during failure. I hope you will consider it.

**Comment by svenhjol** [comment]
This wasn't supposed to go live today :( :(
Charm 1.5.9 release is delayed but should be within next 24 hours.

**Comment by Bluberry-Kat** [comment]
> This wasn't supposed to go live today :( :(

I think curseforge will only approve a project if it has an uploaded file, if you want to prevent this happening in the future. I have a couple names I'm parked on for WIP mods.

Good luck with the release!

**Comment by svenhjol** [comment]
It was my mistake. I scheduled everything incorrectly.
1.5.9 is live as of a few minutes ago and should solve the problem. 
[https://www.curseforge.com/minecraft/mc-mods/charm/files/2973470]()

In the next point release of Covalent I'll make sure it's pointing at the right version. Thanks for the report.
